# Use the official Node.js image.
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./

RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port on which the Nuxt app runs
EXPOSE 3000

# Command to start the Nuxt.js app
CMD ["npm", "run", "dev"]
