FROM python:3.11

ENV BOT_TOKEN ${BOT_TOKEN}

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

COPY Agendagramic-bot/.env /app/.env

EXPOSE 8000

CMD [ "python3", "./bot.py" ]
